chore: update golangci-lint to v1.55.2
To resolve the error.

```console
$ make lint
./bin/golangci-lint run --enable=goimports --disable=unused --exclude=S1023,"Error return value" ./tests/...
../../../../../.local/share/aquaproj-aqua/pkgs/http/golang.org/dl/go1.21.5.darwin-arm64.tar.gz/go/src/net/http/internal/chunked.go:79:14: undefined: max (typecheck)
        cr.excess = max(cr.excess, 0)
```